# Generated by Django 4.2.1 on 2023-06-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
