# Generated by Django 4.2.1 on 2023-06-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_remove_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
